[package]
name = "micrograd_demos"
version = "0.1.0"
edition = "2021"

[dependencies]
micrograd = { path = "../micrograd" }
charts = { path = "../charts" }
ndarray = { version = "0.16" }
rand = { version = "0.8" }
rand_chacha = { version = "0.3" }
